### ISSUE TITLE
Vector DB on IC exploration

### ISSUE THREAD

**Issue by komal-sai-yral** [yral-dapp/hot-or-not-backend-canister#344]

**Comment by komal-rs** [comment]
hnsw-rs

- mmap-rs not wasm compatible
    - on removal, other issue of cpu_time::ProcessTime;

Oasys-db
- wasm error

Elna DB 

- build_index is failing after insertion of 100 records in local
<img width="1167" alt="IC VectorDB Exploration Screenshot July 19" src="https://github.com/user-attachments/assets/217c8e5c-3b29-458d-9007-70bb3944b4bc">


usearch

- wasm32 error

Things to try:

- arcmind
- vectune
- hnsw-rs remove cpu_time

**Comment by komal-rs** [comment]
created issues in the crate github. Will be actively tracking usearch WASM support PR - https://github.com/unum-cloud/usearch/pull/331


ic-vectune seems confusing. Vectune on the other hand has to be built after every addition and for 200,000 takes ~20 secs

**Comment by Natasha-GB** [comment]
- Rely on third party for now and monitor issues, if any
- 1 more day on vectune - check incremental indexing
- Unblock Jay's task

**Comment by komal-rs** [comment]
- incremental indexing works
- each insert call takes  ~1-2 secs in local

Issues:
- after roughly 180 vectors in local
	- Exception: Rejected: Error from Canister bkyz2-fmaaa-aaaaa-qaaaq-cai: Canister trapped: unknown
- centroid
	- build_index 
		- Canister exceeded the limit of 40000000000 instructions for single message execution.

**Comment by harshitasrivastav28** [comment]
- Scrap the idea of exploring more on Vectune.
Next Steps:
1. Discord communication to become first tester for commercial use
2. Set notification for pending pull request

**Comment by komal-rs** [comment]
usearch - https://github.com/unum-cloud/usearch/issues/328
discord convo - https://discord.com/channels/1063947616615923875/1265163307858264236/1265535292794998857


oasys - https://github.com/oasysai/oasysdb/issues/106 (they fixed this but another dependency still has compatibity issues)

**Comment by komal-rs** [comment]
Next steps - Check with oasysdb folks about plans to support wasm32
